### ISSUE TITLE
TypeError: 'function' object is not iterable

### ISSUE THREAD

**Issue by Trevo1** [hafiz031/Fruits360-using-Transfer-Learning-by-Feature-Extraction-from-ResNet50#1]
Traceback (most recent call last):
  File "d:\PROJECT\Fruit_Rec\Fruits360-ResNet50\predict.py", line 38, in <module>
    features = model.predict(image)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1456, in predict
    self._make_predict_function()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 378, in _make_predict_function
    **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 3006, in function
    v1_variable_initialization()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 424, in v1_variable_initialization
    for v in variables:
TypeError: 'function' object is not iterable

**Comment by Trevo1** [comment]
Hi author, thanks for the project, when I run predict.py, I get this error. The strange thing is that the first few times the results can be predicted normally, but when nothing has changed, this error occurs and it can no longer run successfully.

**Comment by hafiz031** [comment]
I am able to run it. I have done some modifications. Mainly the standalone `keras` is changed to `tensorflow.keras`. Also, added the `requirements.txt` file. Hope it will help. Also please make sure your test image directory is okay.

**Comment by Trevo1** [comment]
thanks！and I have run it successfully~
